version: '3'

services:
  postgres:
    image: postgres:14.2-alpine
    restart: always
    volumes:
      - /mnt/permanent_storage/postgres-data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=vaultwarden
      - POSTGRES_USER=vaultwarden
    networks:
      - vaultwarden-database-network

  vaultwarden:
    image: vaultwarden/server:1.24.0

    restart: always
    environment:
      - DATABASE_URL=postgresql://vaultwarden:password@postgres/vaultwarden
      - WEBSOCKET_ENABLED=true
      - ADMIN_TOKEN=${vaultwarden_admin_token}

    volumes:
      - /mnt/permanent_storage/vaultwarden-data/:/data

    depends_on:
      - postgres

    networks:
      - reverse-proxy-network
      - vaultwarden-database-network

  nginx-reverse-proxy:
    build: ./nginx-with-certbot-duckdns
    restart: always
    depends_on:
      - vaultwarden
      - duck-dns-refresher
    ports:
      - 443:443
    volumes:
      - ./nginx-with-certbot-duckdns/nginx.conf:/nginx-template.conf:ro
      - /mnt/permanent_storage/letsencrypt/:/etc/letsencrypt/
    environment:
      - DOMAIN=${duck_dns_domain}.duckdns.org
      - EMAIL=${email}
      - DUCK_DNS_TOKEN=b7f01f47-d75c-4f8f-8787-5fa9d58ec666
    networks:
      - reverse-proxy-network

  vaultwarden-backup:
    build: ./vaultwarden-backup
    image: vaultwarden-backup:latest
    restart: always

    volumes:
      - /mnt/permanent_storage/vaultwarden-data/:/vaultwarden-data/:ro
      - /mnt/permanent_storage/letsencrypt/:/letsencrypt/
    
    environment:
      - DATABASE_URL=postgresql://vaultwarden:password@postgres/vaultwarden
      - CRON_EXPRESION=${backup_cron_expresion}
      - BACKUP_BUCKET_NAME=${tf_prefix}-vaultwarden-backups
      - BACKUPS_PASSWORD_SECRET_ID=${tf_prefix}-vaultwarden-backups-password

    networks:
      - auxiliary-network
      - vaultwarden-database-network

    depends_on:
      - postgres
      - vaultwarden

# Multiple networks to isolate services
networks:
  vaultwarden-database-network:
    name: vaultwarden-database-network
  reverse-proxy-network:
    name: reverse-proxy-network
  auxiliary-network:
    name: auxiliary-network
